// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdqdeddshvjlqmefxwzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcWRlZGRzaHZqbHFtZWZ4d3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTYyNjIsImV4cCI6MjA2NTQ3MjI2Mn0.Pakn5zC1iEYLe49C2-Pum4fTAWL3HJmC_r8dd42lV-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);